name: en_passant
description: A Flutter chess app.

# Prevents accidental publication to pub.dev
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# Versioning
version: 1.0.0+1

environment:
  sdk: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  flame: ^1.7.3
  flame_audio: any
  url_launcher: ^6.0.2
  shared_preferences: any
  async: any

  # Cupertino Icons for iOS
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/icons/icon.png"
  image_path_ios: "assets/icons/icon.png"
  adaptive_icon_foreground: "assets/icons/icon_foreground.png"
  adaptive_icon_background: "assets/icons/icon_background.png"

# Flutter configuration
flutter:
  fonts:
    - family: Jura
      fonts:
        - asset: assets/font/Jura-VariableFont_wght.ttf

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/pieces/classic/
    - assets/images/pieces/letters/
    - assets/images/pieces/angular/
    - assets/images/pieces/8-bit/
    - assets/images/pieces/videochess/
    - assets/images/pieces/lewischessmen/
    - assets/images/pieces/mexicocity/
    - assets/audio/piece_moved.mp3